public class Constants {
    //Offer
    public static final String OFF1 = 'Test offer 1';
    public static final String OFF2 = 'Test offer 2';

    //vehicle
    public static final String testAccountName = 'Test Account'; 
    public static final String testSalonName = 'Test Salon';
    public static final String testSalonStatus = 'Otwarty';
    public static final String testSalonTyp = 'samochody osobowe';
    public static final Integer testSalonCapacity = 9999;
    public static final String testSalonStronaInternetowa = 'https://www.google.com';
    public static final String testSalonAddress = 'Ul. Testowa 14, 13-370 Testowice';
    public static final String testVehicleName = 'Test Vehicle';
    public static final Decimal testVehiclePrice = 99;
    public static final String testVehicleBrand = 'Ford';
    public static final String testVehicleModel = 'Mustang';
    public static final String testVehiclePower = '450';
    public static final Decimal testVehicleCombustion = 11.5;
    public static final String testVehicleSN = '965212';
    public static final String testVehicleGenre = 'sportowe';
    public static final String testVehicleStatus = 'nowy';
    public static final Account testAccount = PojazdTriggerTestDataFactory.addTestAccount();
    public static final Salon__c testSalon = PojazdTriggerTestDataFactory.addTestSalon();
    public static final Boolean testTelemetryNormValue = true;
}
